
---
name: Build bootable image
on:
  pull_request:
    branches:
      - perchnet/main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - perchnet/main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build bootable image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Mount BTRFS loopback
        uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140
        with:
          target-dir: "${{ github.workspace }}"
          mount-opts: compress-force=zstd:2
          loopback-free: 0.5
      # These stage versions are pinned by https://github.com/renovatebot/renovate
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install just
        id: install_just
        run: sudo bash -c 'apt-get update && apt-get -y install just'

      - name: Build containerfile
        id: build_containerfile
        run: just build-containerfile

      - name: Generate bootable image
        id: generate_bootable_image
        run: just generate-bootable-image

      - name: Compress bootable image
        id: compress_bootable_image
        run: tar -czvf bootable.tgz bootable.img

      - uses: actions/upload-artifact@v4
        with:
          name: bootable.tgz
          path: bootable.tgz


