
---
name: Build bootable image
on:
  pull_request:
    branches:
      - perchnet/main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - perchnet/main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build bootable image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Mount BTRFS loopback
        uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140
        with:
          target-dir: "${{ github.workspace }}"
          mount-opts: compress-force=zstd:2
          loopback-free: 0.5
      # These stage versions are pinned by https://github.com/renovatebot/renovate
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Build containerfile
        id: build_containerfile
        run: sudo podman build -t "${{ github.event.repository.name }}:latest" .

      - name: Generate bootable image
        id: generate_bootable_image
        run: |
            fallocate -l 20G "./bootable.img"
            sudo podman run \
                --rm --privileged --pid=host \
                -it \
                -v /etc/containers:/etc/containers \
                -v /var/lib/containers:/var/lib/containers \
                -v /dev:/dev \
                -e RUST_LOG=debug \
                -v "./:/data" \
                "${{ github.event.repository.name }}:latest" bootc install to-disk --composefs-backend --via-loopback /data/bootable.img --filesystem "ext4" --wipe --bootloader systemd

      - name: Compress bootable image
        id: compress_bootable_image
        run: tar -czvf bootable.tgz bootable.img

      - uses: actions/upload-artifact@v4
        with:
          name: bootable.tgz
          path: bootable.tgz


